- hosts: all
  remote_user: root
  sudo: yes
  
  
  vars:
    repository_basedir: /home/javi/git/Script_hosting

  vars_files:
    - $repository_basedir/vars/apache/vars.yml
    
  tasks:
    # Install Apache server, a default virtual host and default config files
    - include: $repository_basedir/apache/tasks/setup.yml
  
    # Manage virtual hosts
    - include: $repository_basedir/apache/tasks/vhost_add.yml create_docroot=True vhost=bibi.test.vt docroot=bibi.test.vt
    - include: $repository_basedir/apache/tasks/vhost_del.yml remove_docroot=True vhost=bibi.test.vt docroot=bibi.test.vt

    # Manage apache modules
    - include: $repository_basedir/apache/tasks/module_enable.yml module=rewrite
    - include: $repository_basedir/apache/tasks/module_disable.yml module=rewrite

  handlers:
    - include: $repository_basedir/apache/handlers/handlers.yml
